# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: lastfm-tweeter

frameworkVersion: '2'
useDotenv: false

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline
  - serverless-plugin-typescript

# The `functions` block defines what code to deploy
functions:
  tweetMostPlayedArtists:
    handler: handler.tweetMostPlayedArtists
